config/routes.rb
DiasporaProjectSite::Application.routes.draw do
  devise_for :users

  get 'switch_locale/:locale' => 'i18n#switch_locale', as: :switch_locale

  constraints subdomain: /^(|www)$/i do
  	controller :pages do
	    get :about
	    get :get_involved
	    get :tutorials
	    scope 'getting_started' do
	    	get :sign_up, action: 'getting_started1'
	    	get :interface, action: 'getting_started2'
	    	get :aspects, action: 'getting_started3'
	    	get :connecting, action: 'getting_started4'
	    	get :sharing, action: 'getting_started5'
	    	get :conversations, action: 'getting_started6'
	    	get :finishing, action: 'getting_started7'
	    end
	    get :formatting
	    get :tips
	    get :other_docs
	  end

    root to: 'pages#index'
  end

  constraints subdomain: /^admin$/i do
    mount RailsAdmin::Engine => '/', as: 'rails_admin'
  end

  constraints subomdain: /^blog$/i do
    get 'feed' => 'blog#feed', :as => :news_feed, :defaults => {:format => :atom}
    resources :blog, path: '/', only: [:index, :show]
  end
end

app/models/blogpost.rb
class Blogpost < ActiveRecord::Base
  def to_param
    "#{self.id}-#{self.title}".parameterize
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  respond_to :html, :except => [:feed]
  respond_to :atom, :only => [:feed]

  def show
    @blogpost = Blogpost.find_by_id params[:id]
  end

  def index
    @blogposts = Blogpost.where(:published => true).order(:created_at => :desc)
  end

  def feed
    @blogposts = Blogpost.where(:published => true).order(:created_at => :desc).limit 5
  end
end

app/controllers/i18n_controller.rb
class I18nController < ApplicationController
  def switch_locale
    request.env["HTTP_REFERER"] ||= root_path
    redirect_to :back
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  respond_to :html
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title title, suffix = t(:title)
    if title.blank? || title =~ /home/i
      suffix
    else
      "#{title} - #{suffix}"
    end
  end

  def markdownify text
    Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true).render(text).html_safe
  end
end

app/helpers/i18n_helper.rb
module I18nHelper
  def locale_switcher_entries
    AVAILABLE_LOCALES.map { |key, name|
      locale_switcher_entry key, name
    }.join("\n").html_safe
  end

  def locale_switcher_entry key, name
    content_tag(:li, class: current_locale == key ? 'current' : nil) do
      link_to name, switch_locale_path(locale: key)
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title yield :page_title %></title>

  <meta charset="utf-8">
  <%= favicon_link_tag "favicon.png" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= auto_discovery_link_tag :atom, news_feed_url, {:title => t('newsfeed')} %>
  <%= stylesheet_link_tag 'application', :media => 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <%= link_to root_url(subdomain: false), class: 'brand' do %>
            <%= image_tag 'logo.png', alt: t('title'), title: t('title'), id: 'header-logo' %>
          <% end %>

          <div id="mainnav" class="pull-right">
            <ul class="nav">
              <!-- <li><%= link_to t('pages.about.menu_title'), about_url(subdomain: false) %></li> -->
              <li><%= link_to t('pages.get_involved.menu_title'), get_involved_url(subdomain: false) %></li>
              <li><%= link_to t('pages.blog.menu_title'), blog_index_url(subdomain: 'blog') %></li>
              <li><%= link_to t('.wiki'), 'https://wiki.diasporafoundation.org' %></li>
              <li><%= link_to t('pages.tutorials.menu_title'), tutorials_url(subdomain: false) %></li>
              <!-- <li><%= link_to t('.planet'), 'http://planet.diasporafoundation.org' %></li> -->
            </ul>
            <%= link_to t('buttons.host_pod'), about_url(subdomain: false, anchor: "host"), class: 'btn primary' %>
            <%= link_to t('buttons.join_diaspora'), root_url(subdomain: false, anchor: "get_started"), class: 'btn success' %>
          </div>
        </div>
      </div>
    </div>

    <div id="main-container" class="container-fluid <%= yield :wrapper_class %>">
      <%= yield %>

      <div id="pusher"></div>
    </div>
  </div>

  <footer>
    <div class="container">
      <div class="row">
        <div class="span10" id="links">
          <h4>
            <%= t '.useful_resources' %>
          </h4>
          <div class="span3">
            <ul>
              <li>
                <a href="http://github.com/diaspora/diaspora/">
                  <%= t '.codebase' %>
                </a>
              </li>
              <li>
                <a href="https://wiki.diasporafoundation.org/">
                  <%= t '.documentation' %>
                </a>
              </li>
              <li>
                <a href="http://github.com/diaspora/diaspora/issues">
                  <%= t '.report_bugs' %>
                </a>
              </li>
            </ul>
          </div>

          <div class="span3">
            <ul>
              <li>
                <a href="http://webchat.freenode.net/?channels=diaspora">
                  <%= t '.irc_general' %>
                </a>
              </li>
              <li>
                <a href="http://webchat.freenode.net/?channels=diaspora-dev">
                  <%= t '.irc_development' %>
                </a>
              </li>
            </ul>
          </div>

          <div class="span3">
            <ul>
              <li>
                <a href="http://groups.google.com/group/diaspora-discuss">
                  <%= t '.discussion_general' %>
                </a>
              </li>
              <li>
                <a href="http://groups.google.com/group/diaspora-dev">
                  <%= t '.discussion_development' %>
                </a>
              </li>
            </ul>
          </div>
        </div>

        <div id="locale-switcher" class="span4">
          <div class="btn-group">
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
              <%= t '.choose_language' %>
            </a>

            <ul class="dropdown-menu">
              <%= locale_switcher_entries %>
              <li>
              	<a href="https://wiki.diasporafoundation.org/Contribute_translations">
              		<%= t '.translate' %>
              	</a>
              </li>
            </ul>
          </div>
        </div>

        <div class="row" id="CC-licence">
          <div class="span16">
            <a rel="license" href="http://creativecommons.org/licenses/by/3.0/">
              <%= image_tag '80x15.png', alt: t('.cc_license_alt') %>
            </a>
            <%= t('.licensed_under', site_link: '
            <a href="https://diasporafoundation.org/" property="cc:attributionName"
               rel="cc:attributionURL">
              diasporafoundation.org
            </a>', license_link: %Q{
            <a rel="license" href="http://creativecommons.org/licenses/by/3.0/">
              #{t('.license_link_text')}
            </a>.}).html_safe %>
          </div>
        </div>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/pages/getting_started1.html.erb
<% content_for :page_title, t('.menu_title') %>
<% content_for :wrapper_class, "index_page" %>

<div id="masthead", class="hero">
  <div class="container">
    <h1><%= t 'pages.tutorials.started_head' %></h1>
    <h2><%= t '.byline' %></h2>
  </div>
</div>

<div class="container">
  <div class="row top_spacing">
    <div class="span2">&nbsp;
    </div>
    <div class="span12">       
        <p class="more-info"><%= t '.welcome' %></p>
        <h3><%= t '.find_pod' %></h3>
		<p><%= t('.find_pod_ex1').html_safe %></p>
        <p class="more-info"><%= t('.find_pod_ex2').html_safe %></p>
		<p><%= t('.find_pod_ex3', wiki_link: link_to(t('.wiki_link_text'), "https://wiki.diasporafoundation.org/Choosing_a_pod")).html_safe %></p>
        <p><%= t '.find_pod_ex4' %></p>
        <p class="more-info"><%= t '.find_pod_ex5' %></p>
		<h3><%= t '.registration' %></h3>
        <p><%= t('.registration1').html_safe %></p>
        <p><%= t '.registration2' %></p>

		<div align="center"><%= image_tag "signup.png" %></div>

		<p><%= t('.registration3').html_safe %></p>
        <p class="more-info"><%= t('.registration4', dhq_link: link_to(t('.dhq_link_text'), "http://dia.so/diasporahq"), part4_link: link_to(t('pages.tutorials.part4'), connecting_path)).html_safe %></p>
        <p><%= t '.registration5' %></p>
        
        <div align="center"><%= image_tag "gettingstarted.png" %></div>
		<p>&nbsp;</p>
	        <ol>
    		    <li><%= t '.registration6' %></li>
		        <li><%= t '.registration7' %></li>
		        <li><%= t '.registration8' %></li>
        		<li><%= t '.registration9' %></li>
		        <li><%= t('.registration10').html_safe %></li>
        	</ol>

		<p><%= t('.profile1').html_safe %></p>
        <p><%= t '.profile2' %></p>
        <div align="center"><%= image_tag "profile-public.png" %></div>
        <div align="center"><%= image_tag "profile-private.png" %></div>
        <%= t('.profile3', part7_link: link_to(t('pages.tutorials.part7'), finishing_path)).html_safe %></p>
        <p><%= t('.profile4').html_safe %></p>
        
        <h3><%= t '.finish' %></h3>
        <p><%= t('.finish_ex1').html_safe %></p>
        <p>&nbsp;</p>
        <p class="more-info"><%= t('.finish_ex2', part5_link: link_to(t('pages.tutorials.part5'), sharing_path)).html_safe  %></p>

        <p>&nbsp;</p>
 
        <p align="center"><%= link_to t('pages.getting_started2.byline'), interface_url %></p>
	</div>
    <div class="span2">
    </div>
  </div>
</div>

app/views/pages/getting_started2.html.erb
<% content_for :page_title, t('.menu_title') %>
<% content_for :wrapper_class, "index_page" %>

<div id="masthead", class="hero">
  <div class="container">
    <h1><%= t 'pages.tutorials.started_head' %></h1>
    <h2><%= t '.byline' %></h2>
  </div>
</div>

<div class="container">
  <div class="row top_spacing">
    <div class="span2">&nbsp;
    </div>
    <div class="span12">       
        <p><%= t('.interface1').html_safe %></p>
		<p class="more-info"><%= t '.interface2' %></p>
        <p><%= t '.interface3' %></p>
        <p><%= t '.header' %></p>
        <div align="center"><%= image_tag "dropdown.png" %></div>
	        <ol>
	    	    <li><%= t '.header2' %></li>
    	    	<li><%= t '.header3' %></li>
	    	    <li><%= t('.header4', part6_link: link_to(t('pages.tutorials.part6'), conversations_path)).html_safe %></li>
    	    	<li><%= t('.header5', part6_link: link_to(t('pages.tutorials.part6'), conversations_path)).html_safe %></li>
    	    	<li><%= t('.header6', part4_link: link_to(t('pages.tutorials.part4'), connecting_path)).html_safe %></li>
		        <li><%= t '.header7' %>
    		    	<ul>
    		    		<li><%= t('.header8', part1_link: link_to(t('pages.tutorials.part1'), sign_up_path)).html_safe %></li>
        				<li><%= t('.header9', part4_link: link_to(t('pages.tutorials.part4'), connecting_path)).html_safe %></li>
            			<li><%= t('.header10', part7_link: link_to(t('pages.tutorials.part7'), finishing_path)).html_safe %></li>
		            	<li><%= t '.header11' %></li>
		            	<li><%= t '.header12' %></li> 
		        	</ul>
		        </li>
    	    </ol>
        <p><%= t '.columns' %></p>
        <div align="center"><%= image_tag "stream.jpg" %></div>
        <p>&nbsp;</p>
        	<ul>
		        <li><%= t('.column1').html_safe %></li>
    		    <li><%=(t '.column2', part4_link: link_to(t('pages.tutorials.part4'), connecting_path)).html_safe %></li>
        		<li><%= t '.column3' %></li>
	        </ul>
        <p><%= t '.views' %></p>
        <h3><%= t '.stream' %></h3>
        <p><%= t '.stream_ex' %></p>
	        <ol>
    		    <li><%= t '.stream1' %></li>
				<li><%= t '.stream2' %></li>
		        <li><%= t '.stream3' %></li>
        	</ol>
        <p><%= t '.stream_ex2' %></p>

        <h3><%= t '.activity' %></h3>
        <p><%= t '.activity_ex' %></p>
        
        <h3><%= t '.mentions' %></h3>
        <p><%= t('.mentions_ex', part4_link: link_to(t('pages.tutorials.part4'), connecting_path)).html_safe %></p>
        
        <h3><%= t '.aspects' %></h3>
        <p><%= t '.aspects_ex1' %></p>
        <p><%= t('.aspects_ex2').html_safe %></p>

		<h3><%= t '.tags' %></h3>
		<p><%= t('.tags_ex1', part5_link: link_to(t('pages.tutorials.part5'), sharing_path)).html_safe %></p>
		<p><%= t('.tags_ex2').html_safe %></p>

        <h3><%= t '.profile' %></h3>
		<p><%= t('.profile_ex1', part1_link: link_to(t('pages.tutorials.part1'), sign_up_url)).html_safe %></p>
		<p><%= t '.profile_ex2' %></p>
		<p><%= t('.profile_ex3').html_safe %></p>
		<p><%= t '.profile_ex4' %></p>        
        <div align="center"><%= image_tag "profile-icons.png" %></div>        
		<p><%= t '.profile_ex5' %></p>
		<p><%= t '.profile_ex6' %></p>
        <p>&nbsp;</p>
		<p class="more-info"><%= t '.finish' %></p>
		
        <p>&nbsp;</p>
 
        <p align="center"><%= link_to t('pages.getting_started1.byline'), sign_up_url %> | <%= link_to t('pages.getting_started3.byline'), aspects_url %></div>
    <div class="span2">
    </div>
  </div>
</div>

app/views/pages/getting_started3.html.erb
<% content_for :page_title, t('.menu_title') %>
<% content_for :wrapper_class, "index_page" %>

<div id="masthead", class="hero">
  <div class="container">
    <h1><%= t 'pages.tutorials.started_head' %></h1>
    <h2><%= t '.byline' %></h2>
  </div>
</div>

<div class="container">
  <div class="row top_spacing">
    <div class="span2">&nbsp;
    </div>
    <div class="span12">       
        <p><%= t '.aspects1' %></p>
		<p><%= t '.aspects2' %></p>
        <p><%= t '.aspects3' %></p>
        <p><%= t('.aspects4').html_safe %></p>
        <div align="center"><%= image_tag "add-aspect.png" %></div>
	        <ol>
    		    <li><%= t '.add_aspect1' %></li>
		        <li><%= t '.add_aspect2' %></li>
		        <li><%= t('.add_aspect3').html_safe %></li>
	        </ol>
        <p><%= t '.add_aspect4' %></p>
    </div>
    <div class="span2">&nbsp;</div>
  </div>
        
  <div class="row">
    <div class="span2">&nbsp;</div>
    <div class="span10">
        <p><%=(t '.my_aspects1').html_safe %></p>
        <ul>
        	<li><%= t '.my_aspects2' %></li>
            <li><%= t '.my_aspects3' %></li>
            <li><%= t '.my_aspects4' %></li>
            <li><%=(t '.my_aspects5').html_safe %></li>
        </ul>
        <p><%= t '.my_aspects6' %></p>
        <p><%= t '.my_aspects7' %></p>
	        <ol>
    		    <li><%= t('.my_aspects8').html_safe %></li>
		        <li><%= t '.my_aspects9' %></li>
			</ol>
    </div>
    <div class="span4"><%= image_tag "aspect-list.png" %></div>
  </div>
  
  <div class="row">
	<div class="span2">&nbsp;</div>
    <div class="span12">
        <h3><%= t '.contacts' %></h3>
        <p><%= t('.contact_ex1', part2_link: link_to(t('pages.tutorials.part2'), interface_path)).html_safe %></p>
        <p><%= t '.contact_ex3' %></p>
        <p><%= t('.contact_ex4').html_safe %></p>  
        <p><%= t '.contact_ex5' %></p>
        <p><%= t '.contact_ex6' %></p>
        <p><%= t '.contact_ex7' %></p>
        
        <h5><%= t '.sharing_me' %></h5>
        <p><%= t '.sharing_me_ex' %></p>
        
        <p>&nbsp;</p>
        <p class="more-info"><%= t '.finish' %></p>
        
        <p>&nbsp;</p>
 
        <p align="center"><%= link_to t('pages.getting_started2.byline'), interface_url %> | <%= link_to t('pages.getting_started4.byline'), connecting_url %></p>
       
    <div class="span2">
    </div>
  </div>
</div>

app/views/pages/getting_started5.html.erb
<% content_for :page_title, t('.menu_title') %>
<% content_for :wrapper_class, "index_page" %>

<div id="masthead", class="hero">
  <div class="container">
    <h1><%= t 'pages.tutorials.started_head' %></h1>
    <h2><%= t '.byline' %></h2>
  </div>
</div>

<div class="container">
  <div class="row top_spacing">
    <div class="span2">&nbsp;
    </div>
    <div class="span12">       
        <p class="more-info"><%= t '.intro1' %></p>
        <p class="more-info"><%= t('.intro2', part6_link: link_to(t('pages.tutorials.part6'), conversations_url)).html_safe %></p>
        
        <h3><%= t '.publisher' %></h3>
        <p><%= t '.publisher_ex1' %></p>
        <p><%= t '.publisher_ex2' %></p>
        <div align="center"><%= image_tag "publisher.png" %></div>
        <p><%= t '.publisher_ex3' %></p>
        <p><%= t('.publisher_ex4').html_safe %></p>
        <p><%= t '.buttons' %></p>
        </div>
        <div class="span2">&nbsp;
        </div>
    </div>

	<div class="row">
    	<div class="span2">&nbsp;
        </div>

    	<div class="span10">
        <h5><%= t '.aspect_selector' %></h5>
        <p><%= t '.aspect_selector_ex1' %></p>
        <p><%= t('.aspect_selector_ex2', part3_link: link_to(t('pages.tutorials.part3'), aspects_path)).html_safe %></p>
        <h5><%= t '.photo' %></h5>
        </div>
        <div class="span4">
        <div align="center"><%= image_tag "aspects_select.png" %></div>
        </div>
	</div>
    <div class="row">
    	<div class="span2">&nbsp;
        </div>
    	<div class="span12">
        <p><%= t '.photo_ex' %></p>
        
        <h5><%= t '.locator' %></h5>
        <p><%= t '.locator_ex1' %></p>
        <p><%= t '.locator_ex2' %></p>
        <p class="more-info"><%= t '.locator_ex3' %></p>
        
        <h5><%= t '.connected' %></h5>
        <p><%= t '.connected_ex1' %></p>
        <p><%= t '.connected_ex2' %></p>
        <p><%= t('.connected_ex3', part7_link: link_to(t('pages.tutorials.part7'), finishing_path)).html_safe %></p>
        
        <h5><%= t '.preview' %></h5>
        <p><%= t '.preview_ex1' %></p>
        <p class="more-info"><%= t '.preview_ex2' %></p>
        
        <h3><%= t '.features' %></h3>
        <h5><%= t '.tags' %></h5>
        <p><%= t '.tags_ex1' %></p>
        <p><%= t '.tags_ex2' %></p>
        <p class="more-info"><%= t('.tags_ex3', part7_link: link_to(t('pages.tutorials.part7'), finishing_path)).html_safe %></p>

        <h5><%= t '.mentions' %></h5>
        <p><%= t '.mentions_ex1' %></p>
        <div align="center"><%= image_tag "mentions.png" %></div>
        <p>&nbsp;</p>
        <p><%= t '.mentions_ex2' %></p>
        <p class="more-info"><%= t '.mentions_ex3' %></p>
        
        <h5><%= t '.format' %></h5>
        <p><%= t('.format_ex', format_link: link_to(t('.format_link_text'), formatting_path)).html_safe %></p>
        
        <h5><%= t '.links' %></h5>
        <p><%= t('.links_ex').html_safe %></p>
        
        <h5><%= t '.embed' %></h5>
        <p><%= t '.embed_ex1' %></p>
        <p class="more-info"><%= t('.embed_ex2').html_safe %></p>
        <h5><%= t '.services' %></h5>
        </div>
        <div class="span2">&nbsp;
        </div>
    </div>

	<div class="row">
    	<div class="span2">&nbsp;
        </div>

    	<div class="span10">
        <p><%= t '.services_ex1' %></p>
        <p><%= t '.services_ex2' %></p>
        <p><%= t '.services_ex3' %></p>
        </div>
        <div class="span4">
        <div align="center"><%= image_tag "connected_services.png" %></div>
        </div>
	</div>
    <div class="row">
    	<div class="span2">&nbsp;
        </div>
    	<div class="span12">
        <p>&nbsp;</p>
        <p><%= t '.how' %></p>
        <p><%= t '.try_out' %></p>
        <p><%= t('.make_post1').html_safe %></p>
        <blockquote><%= t '.make_post2' %></blockquote>
        <p class="more-info"><%= t '.make_post3' %></p>
        
        <h3><%= t '.interact' %></h3>
        <p><%= t '.interact_ex1' %></p>
        <p class="more-info"><%= t('.interact_ex2').html_safe %></p>
        
        <h5><%= t '.comments' %></h5>
        <p><%= t('.comments_ex').html_safe %></p>
        
        <h5><%= t '.likes' %></h5>
        <p><%= t('.likes_ex1').html_safe %></p>
        <p><%= t('.likes_ex2').html_safe %></p>
        
        <h5><%= t '.reshare' %></h5>
        <p><%= t('.reshare_ex').html_safe %></p>
        
        <h5><%= t '.delete' %></h5>
        <p><%= t('.delete_ex').html_safe %></p>
        
        <h5><%= t '.hide' %></h5>
        <p><%= t('.hide_ex').html_safe %></p>
        
        <h5><%= t '.ignore' %></h5>
        <p><%= t '.ignore_ex1' %></p>
        <p class="more-info"><%= t('.ignore_ex2', part7_link: link_to(t('pages.tutorials.part7'), finishing_path)).html_safe %></p>
        <p>&nbsp;</p>
 
        <p class="more-info"><%= t('.finish').html_safe %></p>

        <p>&nbsp;</p>
 
        <p align="center"><%= link_to t('pages.getting_started4.byline'), connecting_url %> | <%= link_to t('pages.getting_started6.byline'), conversations_url %></p>
       
	</div>   
    <div class="span2">
    </div>
  </div>
</div>

app/views/pages/getting_started7.html.erb
<% content_for :page_title, t('.menu_title') %>
<% content_for :wrapper_class, "index_page" %>

<div id="masthead", class="hero">
  <div class="container">
    <h1><%= t 'pages.tutorials.started_head' %></h1>
    <h2><%= t '.byline' %></h2>
  </div>
</div>

<div class="container">
  <div class="row top_spacing">
    <div class="span2">&nbsp;
    </div>
    <div class="span12">       
        <p class="more-info"><%= t '.intro' %></p>
        
        <h3><%= t '.connect' %></h3>
        <p><%= t '.connect_ex1' %></p>
        <p class="more-info"><%= t '.connect_ex2' %></p>
        <p><%= t('.connect_ex3').html_safe %></p>
        <p><%= t('.connect_ex4', part5_link: link_to(t('pages.tutorials.part5'), sharing_path)).html_safe %></p>
        
        <h3><%= t '.settings' %></h3>
        <p><%= t('.settings_ex1').html_safe %></p>
        <p><%= t '.settings_ex2' %></p>
        
        <h5><%= t '.profile' %></h5>
        <p><%= t('.profile_ex', part1_link: link_to(t('pages.tutorials.part1'), sign_up_path)).html_safe %></p>
        <p><%= t '.account_ex2' %></p>
        <p><%= t('.account_ex3').html_safe %></p>
        
        <h5><%= t '.account' %></h5>
        <p><%= t '.account_ex1' %></p>
        <p><%= t '.account_ex4' %></p>
        
        <h5><%= t '.privacy' %></h5>
        <p><%= t('.privacy_ex', part5_link: link_to(t('pages.tutorials.part5'), sharing_path)).html_safe %></p>
        
        <h5><%= t '.services' %></h5>
        <p><%= t '.services_ex' %></p>
        <p>&nbsp;</p>
        <p><%= t('.finish1').html_safe %></p>
        
        <p>&nbsp;</p>
 
        <p align="center"><%= link_to t('pages.getting_started6.byline'), conversations_url %> | <%= link_to t('pages.tutorials.headline'), tutorials_url %></p>
       
	</div>   
    <div class="span2">
    </div>
  </div>
</div>

app/views/pages/tutorials.html.erb
<% content_for :page_title, t('.menu_title') %>
<% content_for :wrapper_class, "index_page" %>

<div id="masthead", class="hero">
  <div class="container">
    <h1><%= t '.headline' %></h1>
    <h2><%= t '.byline' %></h2>
  </div>
</div>

<div class="container">
  <div class="row top_spacing">
    <div class="span12">
		<p><%= t '.tutorials_ex1' %></p>
		<p><%= t('.tutorials_ex2', podup_link: link_to('Pod Uptime', "http://podupti.me/")).html_safe %></p>
		</div>
        <div class="span4">
        	<%= image_tag "diaspora-handdrawn.png", alt: "diaspora* tutorials" %>
        </div>
	</div>
  <div class="row">
    <div class="span-one-third">
    	<h3><%= t '.started_head' %></h3>
      		<ol>
        		<li><%= link_to t('.started1'), sign_up_url %></li>
		        <li><%= link_to t('.started2'), interface_url %></li>
        		<li><%= link_to t('.started3'), aspects_url %></li>
		        <li><%= link_to t('.started4'), connecting_url %></li>
        		<li><%= link_to t('.started5'), sharing_url %></li>
		        <li><%= link_to t('.started6'), conversations_url %></li>
        		<li><%= link_to t('.started7'), finishing_url %></li>
	      </ol>
    </div>
    <div class="span-one-third">
        <h3><%= t '.additional' %></h3>
            <ul>
                <li><%= link_to t('.formatting'), formatting_url %></li>
            </ul>
    </div>
    <div class="span-one-third">
        <h3><%= t '.more_tutorials' %></h3>
            <ul>
	        	<li><%= t('.other_docs', other_docs_link: link_to(t('.other_docs_link_text'), other_docs_url)).html_safe %></li>
            </ul>
    </div>
  </div>
  	<div class="row">
    	<div class="span3">
	    <p>&nbsp;</p>
        </div>
		<div class="span12">
        <p  class="more-info"><% t '.thanks' %></p>
		</div>
    	<div class="span2">
	    <p>&nbsp;</p>
        </div>
     </div>

</div>